[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Buttonless"
decorations = "None" #for linux also

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "Inconsolata Nerd Font"

size = 18
